### ISSUE TITLE
With great variability comes great responsibility?

### ISSUE THREAD

**Issue by pgrete** [lanl/parthenon#115]
While working on our application side I may have stumbled across an interesting "feature" that we introduced with the `ParArrayND` (please correct me if I'm wrong) and that may be worth some discussion to prevent hard to track bugs.

In the example the advected field is a simple variable (so the fourth dimension is 1)
```cpp
  std::string field_name = "advected";
  Metadata m({Metadata::Cell, Metadata::Independent, Metadata::FillGhost});
  pkg->AddField(field_name, m);
```

if the forth dimension is not 1 (e.g., in case one would like to have a single field that holds all conserved variables) I used
```cpp
  std::string field_name = "cons";
  Metadata m({Metadata::Cell, Metadata::Independent, Metadata::FillGhost},
             std::vector<int>({nhydro}));
  pkg->AddField(field_name, m);
```

Now the `CalculateFluxes` example defines 1D `ql` and `qr` arrays (but as `ParArrayND`)
```cpp
  ParArrayND<Real> ql("ql", maxdim);
  ParArrayND<Real> qr("qr", maxdim);
  ParArrayND<Real> qltemp("qltemp", maxdim);

  // get x-fluxes
  for (int k = ks; k <= ke; k++) {
    for (int j = js; j <= je; j++) {
      // get reconstructed state on faces
      pmb->precon->DonorCellX1(k, j, is - 1, ie + 1, q.data, ql, qr);
```
and the reconstruction implicitly assumes the "one variable for all quantities" in its implementation
```cpp
  const int nu = q.GetDim(4) - 1;

  // compute L/R states for each variable
  for (int n = 0; n <= nu; ++n) {
#pragma omp simd
    for (int i = il; i <= iu; ++i) {
      ql(n, i + 1) = qr(n, i) = q(n, k, j, i);
    }
```
No error was thrown at compile time as everything can be flexibly access through the `ParArrayND` `()` operator.
At run time a `double free or corruption (!prev)` error was thrown that I found quite confusing.
I assume that the sth in the reference counting of the Kokkos Views got mixed up so that the View was deallocated prematurely.

So if this turns our to be correct, I'd like to update the Advection example and also the reconstruction functions in order to use fixed dimensions rather than `ParArrayND`s where the (current) implementation already assumes a certain dimensionality.
In addition, I'd like to add a big warning to the use of `ParArrayND` as datatype for functions whose implementation is based on certain assumptions with respect to dimensionality.
That way a problem would already show up at compile time and the developer is responsible to first extract the right ParArray#D (# being an integer rather than "N") to be used in the function call.

What do you think? (specifically tagging @jdolence and @Yurlungur )

**Comment by jdolence** [comment]
Thanks for pointing out this potential issue @pgrete.  I'll have to think about this a bit more before I'm comfortable suggesting we change requirements.  My immediate thought after I read this was that errors like this could be caught easily with assert statements.  In this case, something sort of like
```c++
assert(q.GetDim(4) == ql.GetDim(2) && q.GetDim(4) == qr.GetDim(2))
```
should work.  I'm not sure this is better than your suggestion, just different, so I thought I'd put it out there.  I'll think about it more.

**Comment by Yurlungur** [comment]
Thanks for bringing this up, @pgrete. I admit I don't quite fully understand the double free error. That said, it's clear why the code segment (and `ParArrayND`'s quiet acceptance of the array) are bugged. Some thoughts:
1. Perhaps the double free is also related to issue #106? What compiler did you use when you encountered this? (I've been meaning to get to this, but been delayed by other things the last couple of days.)
2. If the reference counting in `Kokkos` got confused... that seems a deeper issue than what we're discussing here? For example, we should be able to get the error with a raw array somehow.
3. Right now `ParArrayND` silently performs these accesses. We could enable a debug mode where it tells you when it's being accessed out of rank. That wouldn't be too hard to enable. And it could be fast, since it could only warn you if a compiler flag is set.
4. My feeling is that the nature of the solution is less important than being cognizant of the issue. This is something we should document in the `ParArrayND` documentation. And probably both @pgrete's solution and @jdolence's solution are valid, so long as you do one or the other and are cognizant of it when you do it.

**Comment by pgrete** [comment]
I suggest we put this item on the agenda for discussion tomorrow.

**Comment by Yurlungur** [comment]
I think this is mostly resolved, but I  enjountered something new, which I mention in #143 .
