### ISSUE TITLE
Uniform Grid Performance

### ISSUE THREAD

**Issue by forrestglines** [lanl/parthenon#189]
The performance of Parthenon on GPUs using small mesh blocks on a uniform grid will indicate how well AMR will perform using small meshblocks. It might also be easier to identify performance bottlenecks with a simpler uniform grid setup.

I have three questions I'd like answered:
- [ ]  How does performance scale with smaller meshblocks
- [ ] Does kernel launch overhead hinder performance with small meshblocks
- [ ] Is the parallelization of any kernels limited by register pressure

**Comment by forrestglines** [comment]
I tested AthenaPK's performance ( using the pgrete/kokkosize branch of Parthenon) on a 256^3 uniform grid using meshblocks ranging from 16^3 to 256^3 cube. 

We also have 2 different implementations to compute fluxes in AthenaPK, one using scratch spaces with the approach in the current public version of Athena++, and another implementation without scratch spaces that follows the approach in the old public version of Athena++, which we used in K-Athena. I was able to test using scratch level 0 (where scratch is put in the faster CUDA Shared memory) and scratch level 1 (where scratch is put in DRAM).  On paper,  the implementation using scratch level 0 has the highest performance ceiling since it makes less reads/writes to DRAM. However, it will take some work in the AthenaPK repo to get there.

Here's the performance vs. the meshblock size
![athenaPK_perf](https://user-images.githubusercontent.com/5799640/83672370-23ad4900-a5a4-11ea-9d65-00c18bddbecf.png)

Concerning Parthenon, we're getting a factor of 100 worse performance using very small  meshblocks. This is probably due to not having enough work per kernel to offset kernel launch overhead, since each meshblock is executed in a separate kernel. Using CUDA streams through the `Kokkos::PartitionManager` will mitigate some of this overhead by overlapping it between streams.

**Comment by forrestglines** [comment]
Here is the same same analysis for the 3D advection test example in Parthenon

![parthenon_perf](https://user-images.githubusercontent.com/5799640/83683711-d33de780-a5b3-11ea-91a4-8e3a6b652f3d.png)

**Comment by forrestglines** [comment]
I put up the batch script, data parsing script, and plotting script up in 
https://gitlab.com/forrestglines/perftest_athenapk

**Comment by pgrete** [comment]
I did some further testing as part of #190 and identified a second bottleneck apart from the Buffer Pack functions (I'm currently writing a proof of concept on how we may address those and the first results are encouraging - I should have more info probably tomorrow).

The "new" issue is that there's a significant amount of memcopies between host  and device in Parthenon that we don't see in K-Athena, see following profiling results for a similar problem size and decomposition (64^3 mesh, 32^3 MB, no MPI, single host thread):
Parthenon:
![Screenshot from 2020-06-10 12-11-22](https://user-images.githubusercontent.com/22685568/84255958-98880200-ab13-11ea-9705-891816d329c3.png)
K-Athena:
![Screenshot from 2020-06-10 12-10-43](https://user-images.githubusercontent.com/22685568/84255994-a3db2d80-ab13-11ea-9ca3-8b6dab7bbee9.png)

In addition, there's a kernel in Parthenon that (in the example) above already takes 10% of the overall runtime (third most expensive) and I don't know what it is/what it does (it's not a named kernel):
![Screenshot from 2020-06-10 12-13-11](https://user-images.githubusercontent.com/22685568/84256196-e1d85180-ab13-11ea-88ff-b4c368ce5c85.png)

I'm wondering if this is related to the Variable packing and/or Variable design in general as this is one piece that is not present in K-Athena (where we worked with the equivalent of the raw ParArray as typedefs for Views).

It'd be great if someone could have a closer look at this given that (as far as I can tell) it is an  performance issue unrelated to streams and buffer packing (though it may be more pronounced if calls within the buffer routines make use of the feature/function/kernel that causes this).

Pinging more people who already got in touch with the Kokkos pieces to raise awareness @jdolence @Yurlungur @AndrewGaspar @jmstone

**Comment by pgrete** [comment]
I found that there were some `DeepCopy` that didn't use an execution space in the Variable packing functions and updated that in #190 
However, this did not solve the issue.
The majority of the DoT and HtoD calls above are all synchronous and, thus, result in an effective serialization of all kernels (streams are not overlapping).

**Comment by Yurlungur** [comment]
This is a puzzler. Correct me if I'm wrong---unless we're using UVM, there cannot be any hidden deep copies. Is that correct? Could these be metadata copies from kernel launches?

My grepping finds the following instances of deep copy:
```bash
$ grep -r 'Copy' ./* | grep -v 'Copyright'
./bvals/bvals_interfaces.hpp:  void CopyVariableBufferSameProcess(NeighborBlock &nb, int ssize);
./bvals/bvals_interfaces.hpp:  void CopyFluxCorrectionBufferSameProcess(NeighborBlock &nb, int ssize);
./bvals/bvals_var.cpp://! \fn void BoundaryVariable::CopyVariableBufferSameProcess(NeighborBlock& nb, int ssize)
./bvals/bvals_var.cpp:void BoundaryVariable::CopyVariableBufferSameProcess(NeighborBlock &nb, int ssize) {
./bvals/bvals_var.cpp:void BoundaryVariable::CopyFluxCorrectionBufferSameProcess(NeighborBlock &nb, int ssize) {
./bvals/bvals_var.cpp:      CopyVariableBufferSameProcess(nb, ssize);
./bvals/cc/flux_correction_cc.cpp:        CopyFluxCorrectionBufferSameProcess(nb, p);
./interface/variable.hpp:  std::shared_ptr<CellVariable<T>> AllocateCopy(const bool allocComms = false,
./interface/container_collection.cpp:    if (v->IsSet(Metadata::OneCopy)) {
./interface/container_collection.cpp:      c->Add(v->AllocateCopy());
./interface/container_collection.cpp:    if (v->IsSet(Metadata::OneCopy)) {
./interface/container_collection.cpp:      throw std::runtime_error("Non-oneCopy face variables are not yet supported");
./interface/container_collection.cpp:    if (v->IsSet(Metadata::OneCopy)) {
./interface/container_collection.cpp:      c->Add(v->AllocateCopy());
./interface/sparse_variable.hpp:  std::shared_ptr<SparseVariable<T>> AllocateCopy() {
./interface/sparse_variable.hpp:      sv->Add(v.first, v.second->AllocateCopy());
./interface/sparse_variable.hpp:  // void AddCopy(const std::string& theLabel, SparseVariable<T>& mv);
./interface/metadata.hpp:  PARTHENON_INTERNAL_FOR_FLAG(OneCopy)                                                   \
./interface/variable.cpp:std::shared_ptr<CellVariable<T>> CellVariable<T>::AllocateCopy(const bool allocComms,
./interface/container.cpp:    if (!(metadata.IsSet(Metadata::OneCopy))) {
./interface/variable_pack.hpp:  cv.DeepCopy(host_view);
./interface/variable_pack.hpp:  f1.DeepCopy(host_f1);
./interface/variable_pack.hpp:  f2.DeepCopy(host_f2);
./interface/variable_pack.hpp:  f3.DeepCopy(host_f3);
./interface/variable_pack.hpp:  cv.DeepCopy(host_view);
./mesh/mesh.hpp:  //! \fn void MeshBlock::DeepCopy(const DstType& dst, const SrcType& src)
./outputs/parthenon_hdf5.cpp:        auto v_h = (*v).data.GetHostMirrorAndCopy();
./parthenon_arrays.hpp:  void DeepCopy(const Other &src) {
./parthenon_arrays.hpp:  auto GetMirrorAndCopy(MemSpace const &memspace) {
./parthenon_arrays.hpp:  auto GetHostMirrorAndCopy() { return GetMirrorAndCopy(Kokkos::HostSpace()); }
```

```bash
$ grep -r 'copy' ./* | grep -v 'copyright'
./bvals/bvals.hpp:  // currently, this class friendship is required for copying send/recv buffers between
./bvals/bvals_interfaces.hpp:  //   - POD type: safely copy objects via memcpy, no memory padding in the beginning of
./bvals/bvals_base.cpp:  // copy/set in class the input 6x BoundaryFlag for this local MeshBlock boundaries
./bvals/bvals_var.cpp:  // using source block for deep copy to ensure physics kernels are done
./bvals/bvals_var.cpp:  psource_block->deep_copy(ptarget_bdata->recv[nb.targetid], bd_var_.send[nb.bufid]);
./bvals/bvals_var.cpp:  // need fence here as deep_copy is async
./bvals/bvals_var.cpp:  // using source block for deep copy to ensure physics kernels are done
./bvals/bvals_var.cpp:  psource_block->deep_copy(ptarget_bdata->recv[nb.targetid],
./bvals/bvals_var.cpp:  // need fence here as deep_copy is async
./interface/container_collection.cpp:      // just copy the (shared) pointer
./interface/container_collection.cpp:      // copy the shared pointer
./interface/params.hpp:  // can't copy because we have a map of unique_ptr
./interface/state_descriptor.hpp:  // copy constructor throw error
./interface/sparse_variable.hpp:  /// create a new variable deep copy from variable 'theLabel' in input variable mv
./interface/metadata.hpp:  /** only one copy even if multiple stages */                                           \
./interface/metadata.hpp:  /** Communication arrays are a copy: hint to destructor */                             \
./interface/variable.cpp:// copy constructor
./interface/variable.cpp:  // copy the Metadata and set the SharedComms flag if appropriate
./interface/variable.cpp:      // fluxes, etc are always a copy
./interface/container.cpp:      std::cerr << "Currently one one-copy face fields are supported" << std::endl;
./interface/container.cpp:  // copy in private data
./interface/container.cpp:  // Now copy in the specific arrays
./interface/Doxyfile:# pixels and the maximum width should not exceed 200 pixels. Doxygen will copy
./interface/Doxyfile:# verbatim copy of the header file for each class for which an include is
./interface/Doxyfile:# Doxygen will copy the style sheet files to the output directory.
./interface/Doxyfile:# After copying Eclipse needs to be restarted before the help appears.
./interface/Doxyfile:# MathJax. However, it is strongly recommended to install a local copy of
./interface/Doxyfile:# will copy the style sheet files to the output directory.
./mesh/amr_loadbalance.cpp:// step 7: f2c, same MPI rank, different level (just restrict+copy, no pack/send)
./mesh/amr_loadbalance.cpp:    // copy from old/original/other MeshBlock (pob) to newly created block (pmb)
./mesh/amr_loadbalance.cpp:// step 7: c2f, same MPI rank, different level (just copy+prolongate, no pack/send)
./mesh/mesh_refinement.cpp:  } else { // 1D - no restriction, just copy
./mesh/mesh.hpp:  //  \brief Deep copy between views using the exec space of the MeshBlock
./mesh/mesh.hpp:  void deep_copy(const DstType &dst, const SrcType &src) {
./mesh/mesh.hpp:    Kokkos::deep_copy(exec_space, dst, src);
./mesh/weighted_ave.cpp:      // just deep copy
./mesh/weighted_ave.cpp:      // just deep copy
./outputs/outputs.hpp:  ParArrayND<Real> data; // array containing data (usually shallow copy/slice)
./outputs/outputs.hpp:  // copy constructor and assignment operator (pnext_type, pfirst_data, etc. are shallow
./outputs/outputs.hpp:  OutputType(const OutputType &copy_other) = default;
./outputs/outputs.hpp:  OutputType &operator=(const OutputType &copy_other) = default;
./outputs/parthenon_hdf5.cpp:  auto atype = H5Tcopy(H5T_C_S1);
./parameter_input.cpp:  // copy substring into name, remove white space at end of name
./parameter_input.cpp:  // copy substring into value, remove white space at start and end
./parthenon_arrays.hpp:    Kokkos::deep_copy(d6d_, src.Get());
./parthenon_arrays.hpp:    auto mirror = Kokkos::create_mirror_view_and_copy(memspace, d6d_);
```
Not sure how useful that is.

**Comment by pgrete** [comment]
I also don't suspect this to be some hidden "deep" copies.
Metadata may go in the right direction. Eventually, it's not no the GPU a priori and thus may be part of the captured objects (in K-Athena we directly worked with the Kokkos Views within the kernels so the objects were very lightweight and just contained basic data types).

**Comment by Yurlungur** [comment]
One test to understand the performance impact of metadata might be to build increasingly large structs and measure the cost of kernel launches that capture them. 

If this is the issue, and we need the associated metadata, we could perhaps move the metadata to device ahead of time.

**Comment by Yurlungur** [comment]
> [*] Are the variable packs now cached? IIRC there was a concern in the pull request about overhead and given that the Packs are (in the majority of cases) unchanged between cycles.

Variable packs are cached. See [here](https://github.com/lanl/parthenon/blob/master/src/interface/container.hpp#L344) for the data structures. The internals are split between `container`'s prototype and implementation files.

**Comment by forrestglines** [comment]
After a little debugging, I think it's due to calling `Kokkos::View.label()`, which uses a `DeepCopy`. It might be related to this issue in Kokkos: https://github.com/kokkos/kokkos/issues/2029

**Comment by nmsriram** [comment]
If Kokkos is doing label transfers on the default stream, then the streams code is serialized.  At least that is my interpretation of the ['Implicit Synchronization' section 3.2.6.5.4](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#implicit-synchronization) of the Cuda C++ programming guide.  

Do we know if this is the case?

**Comment by Yurlungur** [comment]
If this is the problem, we could perhaps resolve it by storing labels host-side so `View.label()` never needs to be called.

Somehow I had assumed that was already what Kokkos was doing.

**Comment by forrestglines** [comment]
> If this is the problem, we could perhaps resolve it by storing labels host-side so `View.label()` never needs to be called.
> 
> Somehow I had assumed that was already what Kokkos was doing.

I think we should do this, and I agree that Kokkos should already be doing it. We should store `label` inside `Variable` or inside `Metadata`, so that it's not duplicated in GPU memory with `ParArrayND`

**Comment by Yurlungur** [comment]
> > If this is the problem, we could perhaps resolve it by storing labels host-side so `View.label()` never needs to be called.
> > Somehow I had assumed that was already what Kokkos was doing.
> 
> I think we should do this, and I agree that Kokkos should already be doing it. We should store `label` inside `Variable` or inside `Metadata`, so that it's not duplicated in GPU memory with `ParArrayND`

Agreed. This was actually in `Variable` originally, but I think I actually advocated its removal when we moved to views. That was clearly a mistake on my part. 

It's worth considering whether we want it in `Metadata` or in `Variable`. I'm leaning towards re-introducing it into `Variable`.

**Comment by Yurlungur** [comment]
@nmsriram and I just spoke. He has a [branch](https://github.com/lanl/parthenon/tree/sriram/gpuPi/example/kokkos_pi) where he's been experimenting with performance for `calculate_pi`. 

It looks like all the calls to `View.label()` happen in the pack caching, since the cache uses the variable names. We're going to attempt to write a version of @nmsriram's test that doesn't do this and see if the performance hit disappears. 

@nmsriram is also experimenting with coalescing meshblocks, in case turning this knob is worthwhile. It looks like doing so is actually straightforward thanks to the variable pack infrastructure. We will keep you posted.

**Comment by pgrete** [comment]
Thanks for looking into this.
We just came off a call with Christian and asked if there are other not-so-obvious places for copies between host and device apart from the label and he said no.
So this should reduce the number of place we need to touch in order to address the issue.

Independently, it seems that the caching doesn't (fully) work as expected yet.
I added a print statement at the end of both the MakeFlux and MakeFluxPack functions and this is the output using a single MeshBlock for the entire Mesh
```
cycle=0 time=0.0000000000000000e+00 dt=3.5156250000000001e-03
Called MakeFluxPack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakeFluxPack
cycle=1 time=3.5156250000000001e-03 dt=3.5156250000000001e-03
Called MakeFluxPack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakeFluxPack
cycle=2 time=7.0312500000000002e-03 dt=3.5156250000000001e-03
Called MakeFluxPack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakeFluxPack
cycle=3 time=1.0546875000000001e-02 dt=3.5156250000000001e-03
Called MakeFluxPack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakeFluxPack
cycle=4 time=1.4062500000000000e-02 dt=3.5156250000000001e-03
Called MakeFluxPack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakeFluxPack
cycle=5 time=1.7578125000000000e-02 dt=3.5156250000000001e-03
Called MakeFluxPack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakeFluxPack
cycle=6 time=2.1093750000000001e-02 dt=3.5156250000000001e-03
Called MakeFluxPack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakeFluxPack
cycle=7 time=2.4609375000000003e-02 dt=3.5156250000000001e-03
Called MakeFluxPack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakeFluxPack
cycle=8 time=2.8125000000000004e-02 dt=3.5156250000000001e-03
Called MakeFluxPack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakeFluxPack
cycle=9 time=3.1640625000000006e-02 dt=3.5156250000000001e-03
Called MakeFluxPack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakePack
Called MakeFluxPack
cycle=10 time=3.5156250000000007e-02 dt=3.5156250000000001e-03
```
So it seems the packing functions are actually called between cycles and they include mirrors and deep copies between host and devices (which currently will also result in serialization given that only run a single host thread).

**Comment by Yurlungur** [comment]
Hmm... Interesting. Can you point to exactly which functions you put those in? In the container? Or in `interface/variable_packs.hpp`?

**Comment by pgrete** [comment]
In the `variable_pack.hpp` right before the `return VariableFluxPack<T>(cv, f1, f2, f3, cv_size, fsize);` and `return VariablePack<T>(cv, cv_size);`, respectively.

**Comment by Yurlungur** [comment]
Oof. Ok that's clearly a bug. I will dig in.

**Comment by jdolence** [comment]
@pgrete are you calling `pmb->real_containers.PurgeNonBase()` as in the advection example.  One consequence of that call is that the `VariablePack` objects would need to be recreated for any intermediate state containers you're making.  Either way, I think it's time we remove that from the task list for the advection example since it's usually not what people would want to do.

**Comment by pgrete** [comment]
Good point. I just ran the basic example so the PurgeNonBase was included.
I now commented it out but the pack functions are still called (though MakePack is called three times less often per cycle):
```
cycle=8 time=2.8125000000000004e-02 dt=3.5156250000000001e-03
Called MakeFluxPack
Called MakePack
Called MakePack
Called MakePack
Called MakeFluxPack
cycle=9 time=3.1640625000000006e-02 dt=3.5156250000000001e-03
Called MakeFluxPack
Called MakePack
Called MakePack
Called MakePack
Called MakeFluxPack
cycle=10 time=3.5156250000000007e-02 dt=3.5156250000000001e-03
```

**Comment by jdolence** [comment]
Yes I'm seeing that too.  Trying to diagnose.

**Comment by jdolence** [comment]
Found the problem, which turned out to have nothing to do with caching.  I'll put the fix in #196.

**Comment by pgrete** [comment]
Great! That already addressed a significant bit. The following output I got from merging your branch into #190 (so the latest version of #190 is the thing to use for additional test/experiments):
![Screenshot from 2020-06-12 20-32-23](https://user-images.githubusercontent.com/22685568/84536103-6c27dd80-aced-11ea-899d-0cfe82066c33.png)
All the DtoH memcpy past cycle 0 are gone.
There are still plenty of HtoD memcpy left, which are fortunately async (but start to dominate going to meshblocks <=32^3).
But on the bright side the scaling and overall performance already improved dramatically, e.g., using 64^3 meshblocks for a 256^3 grid is only a performance hit of <50% compared to the factor of >4 previously.

**Comment by pgrete** [comment]
![Screenshot from 2020-06-17 20-31-47](https://user-images.githubusercontent.com/22685568/84935871-aa504300-b0d9-11ea-84aa-bd37a72ad58e.png)

Latest profiling screenshot. I'll talk more about it during the call.

**Comment by forrestglines** [comment]
@pgrete @jdolence  I've been finding these `cudaMemcpy` by just using `cuda-gdb`. I run:
```
cuda-gdb -ex "run" --args ./advection-example -i $PARTHENON_SOURCE/example/advection/parthinput.advection parthenon/mesh/refinement=static
```
Then I halt the debugger midway through (CTRL-c) and break on `cudaMemcpy`
```
(cuda-gdb) break cudaMemcpy
```
then I travel up the stack to figure out why it needs to `cudaMemcpy`. Right now `src/parthenon_arrays.hpp:70` called from `src/interface/variable_pack.hpp:141`  is causing the `cudaMemcpy`

**Comment by forrestglines** [comment]
@jdolence Turns out I was building a different version than I was debugging. Your fix to the caching eliminates the `cudaMemcpy`s.  I don't see `cudaMempy` being called except for data output, as it should. There might be another API call doing host do device transfers. I'll have to look into it some more

**Comment by jdolence** [comment]
thanks for the update @forrestglines.  good to know that that issue was fixed, at least.  if anyone digs in and starts to see what's actually triggering these copies, it would be great to have it posted here so we can knock those out too.

**Comment by pgrete** [comment]
I just tried figuring out where the HtoD async copies calls come from but had not luck in figuring out the right function call for the break in `cuda-gdb` (`cudaMemcpyAsync` didn't work).
Any ideas?
Also, someone the call today mentioned early that he already found the spot (or maybe I misremember).

**Comment by pgrete** [comment]
Here's a new piece in the puzzle.
After yesterday's meeting I started to wonder what the actual baseline is that we're comparing to.
Given that this is the Athena++ public version CPUs I also did some testing on that (GPU is a single Volta and CPU is a single fore of a Gold 6148):
![blub-new](https://user-images.githubusercontent.com/22685568/85028596-91986980-b17b-11ea-907d-bcb6f7ff53fa.png)
That plot contains some good news but also raises a question.
Good news first:
1. The performance bugfixes and the threads and streams definitely improved performance (the red line for reference is our starting point from above).
Now a 256^3 Mesh with 32^3 MeshBlocks incurs a performance penalty of 3x (down from about 17x), which, from my point of view is still not great, but definitely not a showstopper for AMR anymore. (plus there's still obvious room for improvement)
2. Slightly smaller MeshBlocks (e.g., using 8 MeshBlocks per Mesh with multi-thread/stream) actually improves performance (potentially due to hiding launch overhead and host logic, but that's speculation)

Now for the question:
@jmstone is there something in the private version of Athena++ that decreases/hides overhead with small MeshBlocks dramatically (or is there sth wrong with my setup)?
If I compare the plot above (blue line, middle panel, left column) with the one on the paper the same configuration (128^3 Mesh, single core Xeon 6148, hydro with plm and HLLE) looks very similar down to 16^3 (normalized cost of ~2x), but at 8^3 MeshBlocks the paper shows a normalized cost of ~4x whereas I got ~30x).

**Comment by forrestglines** [comment]
@pgrete Yesterday I used `nvprof` in summary mode (i.e. without arguments) to get a summary of API calls (although without streams). I saw that [`cudaMemcpyToSymbolAsync`](http://developer.download.nvidia.com/compute/cuda/2_3/toolkit/docs/online/group__CUDART__MEMORY_g981a3eb36f49cd65e69eb575739ba5d7.html#g981a3eb36f49cd65e69eb575739ba5d7) was high on the list of API calls, which I believe Kokkos is using to move some lambda objects to constant memory. I don't think that would work with multiple streams, so I'm not sure yet if the same calls are used when running with streams. I'm trying that today

Also, these [NVIDIA Docs](http://developer.download.nvidia.com/compute/cuda/2_3/toolkit/docs/online/group__CUDART__MEMORY.html) might be a good reference for all the memory functions in the API.

**Comment by pgrete** [comment]
Yes, I also think that they are related to the Kokkos lambdas, but I still wonder why we don't see them in K-Athena.

**Comment by pgrete** [comment]
I found the HtoD issue!
The problem is using a `CellVariable` within a lambda rather than a `ParArray#D`.
I extended the test case #202 to directly use a `CellVariable` a the timing is pretty bad:
```
Filters: Container Iterator Performance
Mask: raw_array performance: 0.00417466
Mask: nd_array performance: 0.00417628
Mask: nd_array/raw_array 1.00039
Mask: iterate_variables performance: 0.0257374
Mask: iterate_variables/raw_array 6.16516
Mask: iterate_cellvariables performance: 0.0573062
-> Mask: iterate_cellvar/raw_array 13.7272
Mask: view_of_views performance: 0.0041351
Mask: view_of_views/raw_array 0.990523
```
and also a view on the profiling data shows that the API is overwhelmed with async HtoD calls (the 4th kernel is the one using the `CellVariables`:
![Screenshot from 2020-06-19 12-39-16](https://user-images.githubusercontent.com/22685568/85124885-eba43800-b22a-11ea-906b-300b2c461ad8.png)

I'll update #202 later to make sure CellVariables are not captured in any kernel.

**Comment by jdolence** [comment]
Oh man! Yeah, we definitely don’t want to be capturing CellVariables. Is there a way to make that a bug the compiler can catch?

**Comment by jmstone** [comment]
Excellent progress!  I had a question and a comment.  Why did the uniform grid performance drop by 50% on a 256^3 mesh between the original and latest versions (red and orange/purple lines)?  The log plot hides how big a drop this is, it seems worrying to me.  Comment: I believe it was Jonah who found the neighbor find algorithm in Athena++ was taking a lot of time.  Kengo fixed this in the latest (development) version.  Now the MeshBlocks are stored as an array, rather than a linked list (which has implications for #193 I think).  When the MeshBlockTree gets large (when there are lots of MeshBlocks within an MPI rank), then this improves performance and might be the reason why the public version of Athena++ does not perform as well as the plot shown in the method paper.

**Comment by pgrete** [comment]
> Oh man! Yeah, we definitely don’t want to be capturing CellVariables. Is there a way to make that a bug the compiler can catch?

I forwarded that question in the Kokkos channel. Let's see if there's an option.
Independently, I'm thinking of removing the `()` operator from the `CellVariable`s to discourage using them directly.

**Comment by pgrete** [comment]
> Excellent progress! I had a question and a comment. Why did the uniform grid performance drop by 50% on a 256^3 mesh between the original and latest versions (red and orange/purple lines)? The log plot hides how big a drop this is, it seems worrying to me.

I noticed that but haven't had the time to investigate yet (as there were changes both on Parthenon and AthenaPK). It actually may be as simple as wrong proc binding between CPU core and GPU because I ran both tests on different machines at different times (as the focus was on scalability).

> Comment: I believe it was Jonah who found the neighbor find algorithm in Athena++ was taking a lot of time. Kengo fixed this in the latest (development) version. Now the MeshBlocks are stored as an array, rather than a linked list (which has implications for #193 I think). When the MeshBlockTree gets large (when there are lots of MeshBlocks within an MPI rank), then this improves performance and might be the reason why the public version of Athena++ does not perform as well as the plot shown in the method paper.

Good point. That should definitely be addressed. I'll leave that for a discussion in #193 though I think a separate PR for this feature may make reviewing more straightforward/less convoluted in terms of mixing features in a single PR.

**Comment by Yurlungur** [comment]
> I forwarded that question in the Kokkos channel. Let's see if there's an option.
Independently, I'm thinking of removing the () operator from the CellVariables to discourage using them directly.

Interested to hear what the  Kokkos folks say.  Some alternatives I can think of:
- Remove the copy constructor or introduce a data structure that does not copy onto device.  We may want variables to  have a viable  copy constructor, so this one is a little dicey.
- Rather than removing `operator()`, remove all the `KOKKOS_*` decorations.  This won't prevent the class from being captured in lambdas, but  it will prevent it from being useful in a capture. I'm not sure, but it may be enough to make  the copy constructor not `KOKKOS_*`.

**Comment by Yurlungur** [comment]
Given the discussion on the Kokkos Slack, I lean towards the following:
1. Remove all `KOKKOS_*` decorations from `CellVariable`
2. Remove `operator()`

That won't perfectly solve it. But it conveys the intent. Thoughts?

**Comment by pgrete** [comment]
# Summary of current issue/main findings so far:

Scaling is limited by the way the buffer are filled:
- each buffer (up to 57 in AMR) is packed *and* unpacked by an individual kernel call for each `Variable`
- with small MeshBlocks (<= 32^3) a single kernel run is just 4-5 us (about the order of a kernel launch) 

The most straightforward way to address this issue is to have one (optimized) kernel launch to fill all buffers in one go.
A POC of this is implemented in the pgrete/pack-in-one branch (overloading the `SendBoundaryBuffer` and `SetBoundaries` function, see https://github.com/lanl/parthenon/blob/7126109bbea03a53ac14a425155c8c61727c3fff/src/bvals/cc/bvals_cc.cpp#L159)
This POC just works for no-MPI, no-AMR runs.
Some issues I encountered were:
- The info on which data (i.e., index ranges) goes to where (the buffer) needs to get on the device.
  - I addressed this hacking in an array that holds that information (needs Cuda >=10 otherwise it cannot be captured)
  - A potential improvement would be to cache that info on the devices (as it only every changes on AMR loadbalance or refine/derefinement)
- This only partially helps as there was a fence to wait for all the buffer to be filled before signaling completing
  - I addressed this (or am in the process) by using cuda events (we'd need an abstraction for that) so that the host thread can handle other MeshBlocks while the buffers are being filled.
- Even if it's just a single kernel, it's performance is still not great (~90us total now) but this would be a great place to start optimizing.

I also started to experiment with filling the communication buffers on the host (see pgrete/host-buffers branch) hoping that copying the entire MeshBlock asynchronously back and forth to the host could be hidden behind compute kernels in other MeshBlocks.
However, the result was very poor (but scaling great). Potentially, I the copies were not truly hidden yet as I didn't use  "HostPinnedMemory" for the host data, which prevent true asynch copies (at least in older Cuda).

Things I haven't look at but we should keep in mind/explore at some point:
- Packing of `Variables`
- Packing of "MeshBlocks
- Implications for packing/unpacking function of other "Variables" with different structure/indices

**Comment by forrestglines** [comment]
> The most straightforward way to address this issue is to have one (optimized) kernel launch to fill all buffers in one go.
> A POC of this is implemented in the pgrete/pack-in-one branch (overloading the `SendBoundaryBuffer` and `SetBoundaries` function, see
> 
> https://github.com/lanl/parthenon/blob/7126109bbea03a53ac14a425155c8c61727c3fff/src/bvals/cc/bvals_cc.cpp#L159

A working concept? Awesome! I'll have to look into after the meeting.

>     * The info on which data (i.e., index ranges) goes to where (the buffer) needs to get on the device.
>       
>       * I addressed this hacking in an array that holds that information (needs Cuda >=10 otherwise it cannot be captured)
>       * A potential improvement would be to cache that info on the devices (as it only every changes on AMR loadbalance or refine/derefinement)

Can the index ranges be computed inside the kernel from the index range of the whole data and from the number of ghost zones? That would reduce data in constant memory, but I'm not sure if it would hurt register usage. I had an example of that in one of the unit tests. I suppose I'm also the only one that would like a CUDA < 10 implementation.


>     * This only partially helps as there was a fence to wait for all the buffer to be filled before signaling completing
>       
>       * I addressed this (or am in the process) by using cuda events (we'd need an abstraction for that) so that the host thread can handle other MeshBlocks while the buffers are being filled.

What buffers are being waited on? All buffers for a meshblock (so all the variables)? All buffers for all mesh blocks? Where is the synchronization point?

>     * Even if it's just a single kernel, it's performance is still not great (~90us total now) but this would be a great place to start optimizing.

Are all the data access/writes in the kernel coallesced? That would be the first thing I would look at.

**Comment by Yurlungur** [comment]
In parthenon paper. Great work everyone.
