### ISSUE TITLE
Linting in build

### ISSUE THREAD

**Issue by berselius** [lanl/parthenon#206]
Should this be turned off if parthenon is being consumed by something else? I just updated parthenon for the app I'm building on top of it and now it's failing on a lint check in one of the examples.

**Comment by AndrewGaspar** [comment]
You can disable this by setting `PARTHENON_LINT_DEFAULT` to off from your meta-project. We should perhaps turn it off if the project is a subdirectory...

**Comment by AndrewGaspar** [comment]
You can do this by doing something like:
```
set(PARTHENON_LINT_DEFAULT OFF CACHE BOOL "Disable linting in `make all` for Parthenon")
```

**Comment by berselius** [comment]
I looked at the CMake and ended up doing that. I do like the subdirectory idea....

**Comment by pgrete** [comment]
I'm also in favor of this (and while we make that change turn the LINTING for the unit and performance tests off in our CI pipeline given that we have a separate "style" stage.
The latter is important, from my point of view, as I saw a few pipelines fail the unit tests because of the style.
Thus, it's not clear if the changes made during development actually break the code or just the formatting.
Of course, in an ideal world, everyone would also test locally before pushing (so that this would be addressed already before the CI pipeline starts) but we know how it is ;)

**Comment by Yurlungur** [comment]
Linting is no longer a required target. You can just get it with `make lint`. Format with `make format`.
