### ISSUE TITLE
Replace ran2 with standard RNG

### ISSUE THREAD

**Issue by pgrete** [lanl/parthenon#48]
It may be worth replacing the custom RNG implementation `src/utils/ran2.cpp` with one of the standard library.

**Comment by jlippuner** [comment]
What about using `std::mt19937_64`? It's one of the most commonly used PRNG (see https://en.wikipedia.org/wiki/Mersenne_Twister), has a period of `2^19937 -1 ~ 10^6000`, and in my benchmark* it is slightly (8%) faster than the current `ran2`. `std::minstd_rand` is 38% faster than `ran2`, but from what I understand, it produces lower-quality random numbers and its period is only `2^31-1 ~ 10^9`, which is less than `ran2`.

* The performance of the random number generators seems to be compiler-dependent. https://medium.com/@odarbelaeze/how-competitive-are-c-standard-random-number-generators-f3de98d973f0

**Comment by jlippuner** [comment]
Excellent question. One drawback of the Mersenne Twister is that if you run multiple instances with different seeds, they are not sufficiently independent. So the solution is to generate different parameter sets for the MT. A long time ago, I played around with this: http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/MTGP/ It's an implementation of the Mersenne Twister specifically for GPUs that ships with different parameter sets and a support utility to generate more independent parameter sets.

However, doing random numbers in parallel with Kokkos will take some thought, because each MT has state associated with it. So we won't want one state per thread, but perhaps one state per block? That would still be a large number of MTs. The alternative might be one state per SM or something like that, but then we won't get deterministic results because different blocks will get mapped to different SMs.

**Comment by dholladay00** [comment]
Why not use Kokkos’s random number generators?

**Comment by jlippuner** [comment]
In fact, the cuRAND library (CUDA's random number generator library) has one generator based on MTGP: https://docs.nvidia.com/cuda/curand/device-api-overview.html#device-api-overview

**Comment by jlippuner** [comment]
Using Kokkos' RNG would definitely be very straight-forward. However, we'd have to live with the fact:

> Note, getting a state on a Cuda device involves atomics, making it non-deterministic!

Also, it sounds like there would be a different RNG for each thread, which might hurt performance and available device memory quite a bit. We'd have to test it, though.

**Comment by junghans** [comment]
Do you know the max. number of random numbers you need per timestep?

**Comment by dholladay00** [comment]
I know that the IMC folks have used a RNG library called random123 that can be used on GPUs and might not suffer from some of the caveats of the Kokkos RNG. Might be useful to have one of those folks chime in.

**Comment by junghans** [comment]
Yes, I was about to suggest a cyclic random number generator, like `random123`, but you need to know the max. number of random numbers per cycle, e.g. timestep.

**Comment by peteroupc** [comment]
An extensive discussion on random generators (but not necessarily for use in GPUs) is at nest/nest-simulator#1440.

There, I write:

> [T]he [random number engines currently available in C++](https://en.cppreference.com/w/cpp/numeric/random) leave a lot to be desired.  For example, `default_random_engine` has unspecified quality; `mt19937`, `ranlux24`, and `ranlux48` have a bigger-than-necessary state and are [nontrivial to seed](http://www.pcg-random.org/posts/cpp-seeding-surprises.html); and `minstd_rand0` and `minstd_rand` admit too few seeds.  Although `discard_block_engine` and `shuffle_block_engine` can be used to improve a random engine's quality, it's hard to tell whether the quality is improved this way without testing.

Of the five random number engines supported by cuRAND, only four are supported for use on-device (MTGP, Philox, MRG32k3a, and XORWOW), and of these, MTGP requires a [non-trivial initialization process](https://docs.nvidia.com/cuda/curand/device-api-overview.html#bit-generation-2), especially because it uses much more state than the remaining three engines.

In fact, Philox is a counter-based PRNG (from Random123) and is already supported by cuRAND.

**Comment by Yurlungur** [comment]
Resolved by #451
